---
sidebar: sidebar 
permalink: concept_cvs_gcp.html 
keywords: cloud volumes service for gcp, google cloud, cloud volumes, cloud volumes service subscription 
summary: NetApp Cloud Volumes Service for Google Cloud를 사용하면 멀티프로토콜 워크로드를 빠르게 추가할 뿐만 아니라 Windows 기반 및 UNIX 기반 앱을 모두 구축하여 배포할 수 있습니다. 
---
= Google Cloud용 Cloud Volumes Service에 대해 자세히 알아보십시오
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp Cloud Volumes Service for Google Cloud를 사용하면 멀티프로토콜 워크로드를 빠르게 추가할 뿐만 아니라 Windows 기반 및 UNIX 기반 앱을 모두 구축하여 배포할 수 있습니다.



== 주요 기능:

* 온프레미스 및 Google Cloud 간에 데이터 마이그레이션
* 몇 초 만에 볼륨을 1TiB에서 100TiB로 프로비저닝
* 멀티 프로토콜 지원(NFS 또는 SMB 볼륨을 생성할 수 있음)
* 자동화되고 효율적인 스냅샷으로 데이터 보호
* 신속한 클론 복제로 애플리케이션 개발 시간 단축




== 비용

Cloud Volumes Service for Google Cloud에서 생성한 볼륨은 Cloud Manager를 통해 청구되지 않고 서비스에 대한 구독으로 청구됩니다.

link:https://console.cloud.google.com/marketplace/product/endpoints/cloudvolumesgcp-api.netapp.com?q=cloud%20volumes%20service["가격 보기"^]

Cloud Manager에서 Google Cloud용 Cloud Volumes Service 지역 또는 볼륨을 검색하는 데 비용이 부과되지 않습니다.



== 지원 지역

link:https://cloud.google.com/solutions/partners/netapp-cloud-volumes/regional-availability["지원되는 Google Cloud 지역을 봅니다."^]



== 시작하기 전에

Cloud Manager는 기존 Cloud Volumes Service for GCP 구독 및 볼륨을 검색할 수 있습니다. 를 참조하십시오 https://cloud.google.com/solutions/partners/netapp-cloud-volumes/["NetApp Cloud Volumes Service for Google Cloud 설명서"^] 구독을 아직 설정하지 않은 경우



== 도움말 보기

Cloud Manager 채팅을 사용하여 Cloud Volumes Service 작업에 대한 일반적인 질문을 Cloud Manager에서 할 수 있습니다.

Google Cloud용 Cloud Volumes Service에 대한 일반적인 질문은 gcinfo@netapp.com 으로 NetApp의 Google Cloud 팀에 이메일을 보내주십시오.

클라우드 볼륨과 관련된 기술 문제의 경우 Google Cloud Console에서 기술 지원 케이스를 생성할 수 있습니다. 을 참조하십시오 link:https://cloud.google.com/solutions/partners/netapp-cloud-volumes/support["지원을 받는 중입니다"^] 를 참조하십시오.



== 제한 사항

* Cloud Manager는 Cloud Volumes Service 볼륨을 사용할 때 작업 환경 간의 데이터 복제를 지원하지 않습니다.
* Cloud Manager에서 Google Cloud용 Cloud Volumes Service 구독을 삭제할 수 없습니다. Google Cloud Console을 통해서만 이 작업을 수행할 수 있습니다.




== 관련 링크

* https://cloud.netapp.com/cloud-volumes-service-for-gcp["NetApp Cloud Central: Google Cloud용 Cloud Volumes Service"^]
* https://cloud.google.com/solutions/partners/netapp-cloud-volumes/["NetApp Cloud Volumes Service for Google Cloud 설명서"^]

