---
sidebar: sidebar 
permalink: concept_before_you_begin_to_deploy_gfc.html 
keywords: global file cache, core, edge, management server 
summary: 클라우드 및 원격 사무소에 Global File Cache를 구축하기 전에 알아야 할 여러 가지 요구 사항이 있습니다. 
---
= 글로벌 파일 캐시 배포를 시작하기 전에
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
클라우드 및 원격 사무소에 Global File Cache를 구축하기 전에 알아야 할 여러 가지 요구 사항이 있습니다.



== 글로벌 파일 캐시 핵심 설계 고려 사항

요구 사항에 따라 하나 이상의 글로벌 파일 캐시 코어 인스턴스를 배포하여 글로벌 파일 캐시 패브릭을 만들어야 할 수도 있습니다. Core 인스턴스는 분산된 Global File Cache Edge 인스턴스와 데이터 센터 파일 서버 리소스(예: 파일 공유, 폴더 및 파일) 간의 트래픽 코p 역할을 하도록 설계되었습니다.

글로벌 파일 캐시 배포를 설계할 때는 확장, 리소스 가용성 및 이중화 측면에서 환경에 적합한 솔루션을 결정해야 합니다. 글로벌 파일 캐시 코어는 다음과 같은 방식으로 배포할 수 있습니다.

* GFC Core 독립 실행형 인스턴스
* GFC 코어 로드 분산 설계(콜드 대기)


을 참조하십시오 <<Sizing guidelines>> 각 구성에서 지원할 수 있는 Edge 인스턴스의 최대 수와 총 사용자 수를 이해하려면 다음을 수행합니다.

엔터프라이즈 구축에 가장 적합한 옵션을 논의하려면 글로벌 파일 캐시 솔루션 엔지니어에게 문의하십시오.



== 사이징 지침

초기 시스템을 구성할 때 염두에 두어야 할 몇 가지 사이징 가이드라인 비율이 있습니다. 사용 기록이 누적되면 이러한 비율을 다시 검토하여 시스템을 최적으로 사용하고 있는지 확인해야 합니다. 여기에는 다음이 포함됩니다.

* 글로벌 파일 캐시 에지/코어 비율
* 분산된 사용자/글로벌 파일 캐시 에지 비율
* 분산 사용자/글로벌 파일 캐시 코어 비율




=== 코어 인스턴스당 에지 인스턴스 수입니다

글로벌 파일 캐시 코어 인스턴스당 최대 10개의 에지 인스턴스를 권장하며, 글로벌 파일 캐시 코어 인스턴스당 최대 20개의 엣지 인스턴스를 권장합니다. 이는 가장 일반적인 워크로드의 유형과 평균 파일 크기에 따라 상당한 차이가 있습니다. 일반적인 작업 부하가 더 많은 경우 코어당 Edge 인스턴스를 더 추가할 수 있지만 이러한 경우에는 NetApp Support에 문의하여 파일 세트의 유형 및 크기에 따라 Edge 및 Core 인스턴스 수를 올바르게 지정해야 합니다.


NOTE: 여러 Global File Cache Edge 및 Core 인스턴스를 동시에 활용하여 요구 사항에 따라 인프라를 확장할 수 있습니다.



=== Edge 인스턴스당 동시 사용자 수입니다

Global File Cache Edge는 캐싱 알고리즘 및 파일 레벨 차이 측면에서 많은 작업을 처리합니다. 단일 Global File Cache Edge 인스턴스는 전용 물리적 Edge 인스턴스당 최대 400명의 사용자와 최대 200명의 전용 가상 구축 사용자를 지원할 수 있습니다. 이는 가장 일반적인 워크로드의 유형과 평균 파일 크기에 따라 상당한 차이가 있습니다. 대규모 공동 작업 파일 유형의 경우 물리적 또는 가상 배포에 따라 Global File Cache Edge 하위 경계당 최대 사용자의 50%를 지정합니다. 평균 파일 크기가 1MB 미만인 보다 일반적인 Office 항목의 경우 물리적 또는 가상 배포에 따라 전역 파일 캐시 에지 상한 경계당 100% 사용자를 안내합니다.


NOTE: Global File Cache Edge는 가상 또는 물리적 인스턴스에서 실행 중인지 여부를 감지하여 로컬 가상 파일 공유에 대한 SMB 접속 수를 최대 200개 또는 400개의 동시 접속으로 제한합니다.



=== Core 인스턴스당 동시 사용자 수입니다

Global File Cache Core 인스턴스는 확장성이 매우 뛰어나며 권장되는 동시 사용자 수는 Core당 3,000명입니다. 이는 가장 일반적인 워크로드의 유형과 평균 파일 크기에 따라 상당한 차이가 있습니다.

엔터프라이즈 구축에 가장 적합한 옵션을 논의하려면 글로벌 파일 캐시 솔루션 엔지니어에게 문의하십시오.



== 필수 구성 요소

이 섹션에 설명된 사전 요구 사항은 클라우드에 설치된 구성 요소, 즉 글로벌 파일 캐시 관리 서버 및 글로벌 파일 캐시 Core에 대한 것입니다.

Global File Cache Edge 사전 요구 사항에 대해 설명합니다 link:download_gfc_resources.html#global-file-cache-edge-requirements["여기"].



=== Cloud Manager 인스턴스

Cloud Volumes ONTAP for Azure를 스토리지 플랫폼으로 사용할 경우 Cloud Manager에 최신 에 표시된 사용 권한이 있는지 확인하십시오 https://occm-sample-policies.s3.amazonaws.com/Policy_for_cloud_Manager_Azure_3.8.7.json["Azure에 대한 Cloud Manager 정책"^].

새로 생성된 인스턴스에는 기본적으로 필요한 모든 권한이 있습니다. 버전 3.8.7(2020년 8월 3일) 이전에 인스턴스를 배포한 경우 해당 항목을 추가해야 합니다.

[source, json]
----
"Microsoft.Resources/deployments/operationStatuses/read",
"Microsoft.Insights/Metrics/Read",
"Microsoft.Compute/virtualMachines/extensions/write",
"Microsoft.Compute/virtualMachines/extensions/read",
"Microsoft.Compute/virtualMachines/extensions/delete",
"Microsoft.Compute/virtualMachines/delete",
"Microsoft.Network/networkInterfaces/delete",
"Microsoft.Network/networkSecurityGroups/delete",
"Microsoft.Resources/deployments/delete",
----


=== 스토리지 플랫폼(볼륨)

백엔드 스토리지 플랫폼(이 경우 배포된 Cloud Volumes ONTAP 인스턴스)은 SMB 파일 공유를 제공해야 합니다. 글로벌 파일 캐시를 통해 노출되는 모든 공유는 Everyone 그룹이 공유 수준에서 모든 권한을 완전히 제어할 수 있도록 하고 NTFS 권한을 통해 권한을 제한해야 합니다.

Cloud Volumes ONTAP 인스턴스에 SMB 파일 공유를 하나 이상 설정하지 않은 경우 설치 중에 이 정보를 구성할 수 있도록 다음 정보가 준비되어 있어야 합니다.

* Active Directory 도메인 이름, 이름 서버 IP 주소, Active Directory 관리자 자격 증명.
* 생성할 볼륨의 이름 및 크기, 볼륨을 생성할 애그리게이트의 이름 및 공유 이름


데이터 세트가 증가해도 그에 따라 확장할 수 있는 기능과 함께 애플리케이션의 전체 데이터 세트를 수용할 수 있을 만큼 볼륨을 크게 설정하는 것이 좋습니다. 작업 환경에 Aggregate가 여러 개 있는 경우 를 참조하십시오 link:task_managing_storage.html["기존 애그리게이트 관리"^] 새 볼륨에 사용할 수 있는 공간이 가장 많은 애그리게이트를 확인합니다.



=== 글로벌 파일 캐시 관리 서버

이 글로벌 파일 캐시 관리 서버는 클라우드 공급자 구독 서비스에 연결하고 다음 URL에 액세스하려면 HTTPS(TCP 포트 443)를 통한 외부 액세스가 필요합니다.

* https://talonazuremicroservices.azurewebsites.net["https://talonazuremicroservices.azurewebsites.net"]
* https://talonlicensing.table.core.windows.net["https://talonlicensing.table.core.windows.net"]


이 포트는 글로벌 파일 캐시 소프트웨어가 제대로 작동하려면 모든 WAN 최적화 장치 또는 방화벽 제한 정책에서 제외되어야 합니다.

또한 글로벌 파일 캐시 관리 서버는 인스턴스에 대해 고유한(지리적) NetBIOS 이름을 필요로 합니다(예: GFC-MS1).


NOTE: 하나의 관리 서버가 서로 다른 작업 환경에 배포된 여러 개의 글로벌 파일 캐시 코어 인스턴스를 지원할 수 있습니다. Cloud Manager에서 구축할 경우, 각 작업 환경에 고유한 개별 백엔드 스토리지가 있으며 동일한 데이터가 포함되지 않습니다.



=== 글로벌 파일 캐시 코어

이 글로벌 파일 캐시 코어는 TCP 포트 범위 6618-6630에서 수신 대기합니다. 방화벽 또는 네트워크 보안 그룹(NSG) 구성에 따라 인바운드 포트 규칙을 통해 이러한 포트에 대한 액세스를 명시적으로 허용해야 할 수 있습니다. 또한 이러한 포트는 글로벌 파일 캐시 소프트웨어가 제대로 작동하려면 모든 WAN 최적화 장치 또는 방화벽 제한 정책에서 제외되어야 합니다.

글로벌 파일 캐시 핵심 요구 사항은 다음과 같습니다.

* 인스턴스의 고유한(지리적) NetBIOS 이름(예: GFC-core1)
* Active Directory 도메인 이름입니다
+
** 글로벌 파일 캐시 인스턴스는 Active Directory 도메인에 가입되어야 합니다.
** 글로벌 파일 캐시 인스턴스는 글로벌 파일 캐시 특정 조직 구성 단위(OU)에서 관리해야 하며 상속된 회사 GPO에서 제외해야 합니다.


* 서비스 계정. 이 글로벌 파일 캐시 Core의 서비스는 특정 도메인 사용자 계정으로 실행됩니다. 서비스 계정이라고도 하는 이 계정은 글로벌 파일 캐시 코어 인스턴스와 연결될 각 SMB 서버에 대해 다음 권한을 가지고 있어야 합니다.
+
** 프로비저닝된 서비스 계정은 도메인 사용자여야 합니다.




네트워크 환경의 제한 수준 및 GPO에 따라 이 계정에는 도메인 관리자 권한이 필요할 수 있습니다.

* "서비스로 실행" 권한이 있어야 합니다.
* 암호는 "만료되지 않음"으로 설정해야 합니다.
* "다음 로그온할 때 반드시 암호 변경" 계정 옵션을 비활성화(선택 해제)해야 합니다.
* 백엔드 파일 서버 기본 제공 Backup Operators 그룹의 구성원이어야 합니다(Cloud Manager를 통해 구축할 경우 자동으로 활성화됨).




=== 라이센스 관리 서버

* 글로벌 파일 캐시 라이선스 관리 서버(LMS)는 Microsoft Windows Server 2016 Standard 또는 Datacenter Edition 또는 Windows Server 2019 Standard 또는 Datacenter 버전에서 구성해야 합니다. 가능하면 데이터 센터 또는 클라우드의 글로벌 파일 캐시 코어 인스턴스에서 구성해야 합니다.
* 별도의 Global File Cache LMS 인스턴스가 필요한 경우 최신 Global File Cache 소프트웨어 설치 패키지를 원래 버전의 Microsoft Windows Server 인스턴스에 설치해야 합니다.
* LMS 인스턴스는 HTTPS(TCP 포트 443)를 사용하여 가입 서비스(Azure 서비스/공용 인터넷)에 연결할 수 있어야 합니다.
* Core 및 Edge 인스턴스는 HTTPS(TCP 포트 443)를 사용하여 LMS 인스턴스에 연결해야 합니다.




=== 네트워킹

* 방화벽: 글로벌 파일 캐시 엣지와 코어 인스턴스 간에 TCP 포트를 허용해야 합니다.
* 글로벌 파일 캐시 TCP 포트: 443(HTTPS), 6618–6630.
* 네트워크 최적화 장치(예: Riverbed Steelhead)는 글로벌 파일 캐시 특정 포트(TCP 6618-6630)를 통과하도록 구성해야 합니다.

