---
sidebar: sidebar 
permalink: concept_overview.html 
keywords: overview, concepts, features, use case, days, 14 days 
summary: Cloud Manager를 사용하면 IT 전문가 및 클라우드 설계자가 NetApp의 클라우드 솔루션을 사용하여 하이브리드 멀티 클라우드 인프라를 중앙에서 관리할 수 있습니다. 
---
= Cloud Manager에 대해 자세히 알아보십시오
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


Cloud Manager를 사용하면 IT 전문가 및 클라우드 설계자가 NetApp의 클라우드 솔루션을 사용하여 하이브리드 멀티 클라우드 인프라를 중앙에서 관리할 수 있습니다.



== 피처

Cloud Manager는 엔터프라이즈급 SaaS 기반 관리 플랫폼으로, 데이터의 위치에 상관없이 데이터를 제어할 수 있습니다.

* 설정 및 사용 https://cloud.netapp.com/ontap-cloud["Cloud Volumes ONTAP"^] 클라우드 전반에서 효율적인 멀티 프로토콜 데이터 관리
* 파일 스토리지 서비스 설정 및 사용: https://cloud.netapp.com/azure-netapp-files["Azure NetApp Files"^], https://cloud.netapp.com/cloud-volumes-service-for-aws["AWS 환경을 위한 Cloud Volumes Service"^], 및 https://cloud.netapp.com/cloud-volumes-service-for-gcp["Google Cloud용 Cloud Volumes Service"^].
* 볼륨 생성, 클라우드에 백업, 하이브리드 클라우드 간 데이터 복제, 콜드 데이터를 클라우드로 계층화하여 온프레미스 ONTAP 클러스터를 검색하고 관리할 수 있습니다.
* 같은 통합 클라우드 서비스 및 소프트웨어 지원 https://cloud.netapp.com/cloud-compliance["클라우드 규정 준수"^], https://cloud.netapp.com/cloud-insights["Cloud Insights"^], https://cloud.netapp.com/cloud-backup-service["Cloud Backup Service"^], https://netapp.io/persistent-storage-provisioner-for-kubernetes/["트라이던트"^]등.


https://cloud.netapp.com/cloud-manager["Cloud Manager에 대해 자세히 알아보십시오"^].



== 지원되는 오브젝트 스토리지 공급자

Cloud Manager를 사용하면 Amazon Web Services, Microsoft Azure, Google Cloud에서 클라우드 스토리지를 관리하고 클라우드 서비스를 사용할 수 있습니다.



== 비용

Cloud Manager 소프트웨어는 NetApp에서 무료로 제공합니다.

대부분의 작업에서 Cloud Manager는 클라우드 네트워크에 Connector를 배포하라는 메시지를 표시합니다. 그러면 컴퓨팅 인스턴스 및 관련 스토리지에 대한 클라우드 공급자의 요금이 부과됩니다. 구내에서 Connector 소프트웨어를 실행할 수 있는 옵션이 있습니다.



== Cloud Manager의 작동 방식

Cloud Manager에는 NetApp Cloud Central과 통합된 SaaS 기반 인터페이스 및 Cloud Volumes ONTAP 및 기타 클라우드 서비스를 관리하는 커넥터가 포함되어 있습니다.



=== 서비스형 소프트웨어

Cloud Manager는 를 통해 액세스할 수 있습니다 https://cloudmanager.netapp.com["SaaS 기반 사용자 인터페이스"^] API를 사용해 보십시오. 이 SaaS 환경을 통해 최신 기능을 릴리즈할 때 자동으로 액세스하고 Cloud Central 계정과 커넥터 간에 쉽게 전환할 수 있습니다.



=== NetApp Cloud Central에서

https://cloud.netapp.com["NetApp Cloud Central에서"^] 액세스 및 관리를 위한 중앙 집중식 위치를 제공합니다 https://www.netapp.com/us/products/cloud-services/use-cases-for-netapp-cloud-services.aspx["NetApp 클라우드 서비스"^]. 중앙 집중식 사용자 인증을 통해 동일한 자격 증명 세트를 사용하여 Cloud Manager와 Cloud Insights 같은 다른 클라우드 서비스에 액세스할 수 있습니다.

Cloud Manager에 처음 로그인하면 _Cloud Central 계정 _ 을(를) 생성하라는 메시지가 표시됩니다. 이 계정은 다중 테넌시를 제공하며 사용자가 isolated_worksaces_에서 사용자 및 리소스를 구성할 수 있도록 합니다.



=== 커넥터

대부분의 경우 계정 관리자는 클라우드 또는 온-프레미스 네트워크에 _Connector_를 배포해야 합니다. Connector를 사용하면 Cloud Manager에서 퍼블릭 클라우드 환경 내의 리소스와 프로세스를 관리할 수 있습니다.

커넥터는 항상 작동 상태를 유지해야 합니다. 이는 여러분이 제공하는 서비스의 지속적인 상태 및 운영에 중요합니다.

예를 들어, Connector는 Cloud Volumes ONTAP PAYGO 시스템의 상태 및 작동에 있어 핵심 구성 요소입니다. 커넥터가 꺼져 있는 경우, Cloud Volumes ONTAP PAYGO 시스템은 커넥터와의 통신이 14일 이상 끊긴 후 종료됩니다.

link:concept_connectors.html["커넥터가 필요한 시기와 작동 방식에 대해 자세히 알아보십시오"].
