---
sidebar: sidebar 
permalink: concept_backup_to_cloud.html 
keywords: backing up, restoring, back up, backup, restore, cloud volumes ontap, aws, azure, s3, blob, back up volumes, Backup to Cloud, restore volumes, billing, cost, on-premises ONTAP, onprem 
summary: 클라우드 백업 은 ONTAP 및 사내 Cloud Volumes ONTAP 클러스터를 위한 애드온 서비스로, 클라우드 데이터를 보호하기 위한 백업 및 복원 기능과 장기적인 아카이브를 제공합니다. 백업은 거의 복구 또는 클론 복제에 사용되는 볼륨 Snapshot 복사본과 관계없이 클라우드 계정의 오브젝트 저장소에 저장됩니다. 
---
= 클라우드 백업에 대해 자세히 알아보십시오
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
클라우드 백업 은 ONTAP 및 사내 Cloud Volumes ONTAP 클러스터를 위한 애드온 서비스로, 클라우드 데이터를 보호하기 위한 백업 및 복원 기능과 장기적인 아카이브를 제공합니다. 백업은 거의 복구 또는 클론 복제에 사용되는 볼륨 Snapshot 복사본과 관계없이 클라우드 계정의 오브젝트 저장소에 저장됩니다.

클라우드 백업은 에서 제공합니다 https://cloud.netapp.com/cloud-backup-service["Cloud Backup Service"^].


NOTE: 모든 백업 및 복원 작업에 Cloud Manager를 사용해야 합니다. ONTAP 또는 클라우드 공급자로부터 직접 수행된 모든 작업으로 인해 지원되지 않는 구성이 발생합니다.



== 피처

* 데이터 볼륨의 독립 복사본을 클라우드의 저렴한 오브젝트 스토리지에 백업합니다.
* 사용 중인 AES-256비트 암호화 유휴 및 TLS 1.2 HTTPS 연결로 백업 데이터를 보호합니다.
* 클라우드에서 클라우드로, 사내 ONTAP 시스템에서 클라우드로 백업
* 단일 볼륨의 최대 1,019개 백업 지원
* 특정 시점에서 데이터 복원
* 데이터를 소스 시스템의 볼륨이나 다른 시스템으로 복구합니다.




== 지원되는 작업 환경 및 오브젝트 스토리지 공급자

클라우드 백업은 다음과 같은 작업 환경에서 지원됩니다.

* AWS의 Cloud Volumes ONTAP
* Azure의 Cloud Volumes ONTAP
* 온프레미스 ONTAP 클러스터




== 비용

Cloud Backup to Cloud는 BYOL(Bring Your Own License) 및 PAYGO(Pay As You Go)의 두 가지 가격 옵션으로 제공됩니다.

BYOL의 경우 NetApp의 요금을 지불하여 6개월 단위로 최대 용량의 백업 용량(예: 10GB(스토리지 효율성 이전)을 사용할 수 있으며, 오브젝트 스토리지 비용에 대한 클라우드 공급자의 비용을 지불해야 합니다. Cloud Manager 라이센스 페이지에 입력한 일련 번호를 받아 서비스를 활성화할 수 있습니다. 두 제한 중 하나에 도달하면 라이센스를 갱신해야 합니다. 을 참조하십시오 link:task_managing_licenses.html#adding-and-updating-your-backup-byol-license["Backup BYOL 라이센스 추가 및 업데이트"^]. 백업 BYOL 라이센스는 와 관련된 모든 Cloud Volumes ONTAP 시스템에 적용됩니다 .

PAYGO의 경우 클라우드 공급자에게 오브젝트 스토리지 비용을 지불하고 NetApp을 통해 백업 라이센스 비용을 지불해야 합니다. 라이센스 비용은 사용된 용량을 기준으로 함(스토리지 효율성 이전):

* AWS: https://aws.amazon.com/marketplace/pp/B07QX2QLXX["가격 세부 정보는 Cloud Manager Marketplace 오퍼링을 참조하십시오"^].
* Azure(Azure): https://azuremarketplace.microsoft.com/en-us/marketplace/apps/netapp.cloud-manager?tab=Overview["가격 세부 정보는 Cloud Manager Marketplace 오퍼링을 참조하십시오"^].




=== 무료 평가판

30일 무료 평가판을 사용할 수 있습니다. 평가판 사용 시 남은 무료 평가판 사용 일수에 대한 알림이 표시됩니다. 무료 평가판이 끝나면 백업이 생성되지 않습니다. 서비스를 계속 사용하려면 서비스에 가입하거나 라이센스를 구입해야 합니다.

서비스가 비활성화되면 백업이 삭제되지 않습니다. 백업을 삭제하지 않을 경우 클라우드 공급자가 백업 용량에 대한 오브젝트 스토리지 비용을 계속 청구합니다.



== Backup to Cloud의 작동 방식

Cloud Volumes ONTAP 또는 사내 ONTAP 시스템에서 클라우드로 백업을 활성화하면 서비스가 데이터의 전체 백업을 수행합니다. 볼륨 스냅샷은 백업 이미지에 포함되지 않습니다. 초기 백업 후에는 모든 추가 백업이 증분 백업되므로 변경된 블록과 새 블록만 백업됩니다.



=== 백업이 상주하는 위치입니다

백업 복사본은 Cloud Manager에서 클라우드 계정에 만드는 S3 버킷 또는 Azure Blob 컨테이너에 저장됩니다. Cloud Volumes ONTAP 시스템의 경우 Cloud Volumes ONTAP 시스템이 있는 동일한 영역에 오브젝트 저장소가 생성됩니다. 온프레미스 ONTAP 시스템의 경우 서비스를 활성화할 때 지역을 식별합니다.

Cloud Volumes ONTAP 또는 온프레미스 ONTAP 시스템마다 오브젝트 저장소가 하나씩 있습니다. Cloud Manager에서 오브젝트 저장소의 이름은 NetApp-backup-_clusteruuid_입니다

이 오브젝트 저장소를 삭제하지 마십시오.

참고:

* AWS에서 Cloud Manager는 를 지원합니다 https://docs.aws.amazon.com/AmazonS3/latest/dev/access-control-block-public-access.html["Amazon S3 블록 공용 액세스 기능입니다"^] S3 버킷에서.
* Azure에서 Cloud Manager는 Blob 컨테이너용 스토리지 계정이 있는 새 리소스 그룹 또는 기존 리소스 그룹을 사용합니다.




=== 지원되는 S3 스토리지 클래스

Amazon S3에서는 백업이 _Standard_storage 클래스에서 시작되고 30일 후에 _Standard - Infrequent Access_storage 클래스로 전환됩니다.



=== 지원되는 Azure Blob 액세스 계층

Azure에서 각 백업은 _cold_access 계층과 연결됩니다.



=== 백업 설정은 시스템 전체에 적용됩니다

Backup to Cloud를 활성화하면 시스템에서 식별한 모든 볼륨이 클라우드에 백업됩니다.

보존할 백업 스케줄 및 수는 시스템 레벨에서 정의됩니다. 백업 설정은 시스템의 모든 볼륨에 영향을 줍니다.



=== 일정은 매일, 매주, 매월 또는 둘의 조합입니다

모든 볼륨의 일별 또는 주별 또는 월별 백업을 선택할 수 있습니다. 또한 3개월, 1년 및 7년 동안 백업 및 보존을 제공하는 시스템 정의 정책 중 하나를 선택할 수도 있습니다. 이러한 정책은 다음과 같습니다.

[cols="30,20,20,20,30"]
|===
| 정책 이름 3+| 간격당 백업... | 최대 백업 


|  | * 매일 * | * 매주 * | * 매월 * |  


| Netapp3개월 보존 | 30 | 13 | 3 | 46 


| Netapp1YearRetention | 30 | 13 | 12 | 55 


| Netapp7YearsRetention | 30 | 53 | 84 | 167 
|===
범주 또는 간격에 대한 최대 백업 수에 도달하면 오래된 백업이 제거되므로 항상 최신 백업이 유지됩니다.

데이터 보호 볼륨의 백업 보존 기간은 소스 SnapMirror 관계에 정의된 보존 기간과 동일합니다. 원하는 경우 API를 사용하여 변경할 수 있습니다.



=== 백업은 자정에 수행됩니다

* 매일 백업은 매일 자정 직후에 시작됩니다.
* 매주 백업은 일요일 아침 자정이 지난 직후에 시작됩니다.
* 매월 백업은 매월 첫 번째 자정 직후에 시작됩니다.


현재 사용자가 지정한 시간에 백업 작업을 예약할 수 없습니다.



=== 백업 복사본은 Cloud Central 계정과 연결됩니다

백업 복사본은 와 연결됩니다 link:concept_cloud_central_accounts.html["Cloud Central 계정"^] Cloud Manager가 상주하는 위치

동일한 Cloud Central 계정에 여러 Cloud Manager 시스템이 있는 경우 각 Cloud Manager 시스템에 동일한 백업 목록이 표시됩니다. 여기에는 Cloud Volumes ONTAP와 연결된 백업 및 다른 Cloud Manager 시스템의 온프레미스 ONTAP 인스턴스가 포함됩니다.



=== BYOL 라이센스 고려사항

Backup to Cloud BYOL 라이센스를 사용하는 경우 Cloud Manager는 백업이 용량 제한에 도달하거나 라이센스 만료 날짜가 가까워지면 알려줍니다. 다음과 같은 알림을 받게 됩니다.

* 백업이 라이센스 용량의 80%에 도달한 경우 제한에 도달하면 다시 한 번 백업을 수행합니다
* 라이센스가 만료되기 30일 전에 라이센스가 만료되고 라이센스가 만료되면 다시 만료됩니다


Cloud Manager 인터페이스 오른쪽 아래에 있는 채팅 아이콘을 사용하여 알림을 받을 때 라이센스를 갱신하십시오.

라이센스가 만료되면 다음 두 가지 상황이 발생할 수 있습니다.

* ONTAP 시스템에 사용 중인 계정에 Marketplace 계정이 있는 경우 백업 서비스가 계속 실행되지만 PAYGO 라이센스 모델로 이전됩니다. 클라우드 공급자가 오브젝트 스토리지 비용을, NetApp은 백업 라이센스 비용에 대해, 그리고 백업 시 사용 중인 용량에 대해 비용을 청구합니다.
* ONTAP 시스템에 사용 중인 계정에 마켓플레이스 계정이 없는 경우 백업 서비스가 계속 실행되지만 만료 메시지가 계속 표시됩니다.


BYOL 구독을 갱신하면 Cloud Manager는 NetApp에서 새 라이센스를 자동으로 가져와 설치합니다. Cloud Manager가 보안 인터넷 연결을 통해 라이센스 파일에 액세스할 수 없는 경우 직접 파일을 얻고 Cloud Manager에 수동으로 업로드할 수 있습니다. 자세한 내용은 을 참조하십시오 link:task_managing_licenses.html#adding-and-updating-your-backup-byol-license["Backup BYOL 라이센스 추가 및 업데이트"^].

PAYGO 라이센스로 전환된 시스템은 자동으로 BYOL 라이센스로 돌아갑니다. 라이센스 없이 실행 중이던 시스템은 경고 메시지 수신을 중지하고 라이센스가 만료된 동안 발생한 백업에 대해 비용이 청구됩니다.



== 지원되는 볼륨

Backup to Cloud는 읽기-쓰기 볼륨 및 데이터 보호(DP) 볼륨을 지원합니다.

FlexGroup 볼륨은 현재 지원되지 않습니다.



== 제한 사항

* 클라우드 백업을 사용하도록 설정한 경우 SnapLock 또는 사내 시스템에서 WORM 스토리지(Cloud Volumes ONTAP)가 지원되지 않습니다.
* 사내 ONTAP 시스템에서 백업할 때 클라우드 백업 제한:
+
** 사내 클러스터에서 ONTAP 9.7P5 이상이 실행되고 있어야 합니다.
** Cloud Manager는 Azure에 구축해야 합니다. 사내 Cloud Manager 구축에는 지원이 제공되지 않습니다.
** 백업의 대상 위치는 Azure의 오브젝트 스토리지만 사용합니다.
** 백업은 Azure에 구축된 Cloud Volumes ONTAP 시스템에만 복원할 수 있습니다. 백업을 사내 ONTAP 시스템이나 다른 클라우드 공급자를 사용하는 Cloud Volumes ONTAP 시스템으로 복원할 수 없습니다.


* 데이터 보호(DP) 볼륨을 백업할 때 소스 볼륨의 SnapMirror 정책에 정의된 규칙은 허용된 Backup to Cloud 정책 이름 * 일 단위 *, * 주 * 또는 * 월 * 과 일치하는 레이블을 사용해야 합니다. 그렇지 않으면 해당 DP 볼륨에 대한 백업이 실패합니다.
* Azure에서 Cloud Volumes ONTAP를 구축할 때 클라우드로 백업을 활성화하면 Cloud Manager에서 자동으로 리소스 그룹을 생성하고 이를 변경할 수 없습니다. 클라우드로 백업을 설정할 때 고유한 리소스 그룹을 선택하려면 * Cloud Volumes ONTAP를 배포할 때 * 클라우드로 백업 * 을 비활성화한 다음 클라우드로 백업 을 활성화하고 클라우드로 백업 설정 페이지에서 리소스 그룹을 선택합니다.
* Cloud Volumes ONTAP 시스템에서 볼륨을 백업할 때 Cloud Manager 외부에서 생성한 볼륨은 자동으로 백업되지 않습니다.
+
예를 들어, ONTAP CLI, ONTAP API 또는 System Manager에서 볼륨을 생성하는 경우 볼륨이 자동으로 백업되지 않습니다.

+
이러한 볼륨을 백업하려면 Backup to Cloud를 비활성화한 다음 다시 활성화해야 합니다.


