---
sidebar: sidebar 
permalink: reference_key_changes.html 
keywords: 'what"s new, key changes, saas, accounts, workspaces, users, connectors, endpoints, urls, permissions, permission changes' 
summary: 이 페이지에서는 새로운 개선 사항을 도입하여 서비스를 사용하는 데 도움이 되는 Cloud Manager의 _important_changes를 소개합니다. 새로운 기능 및 향상된 기능에 대한 자세한 내용은 새로운 기능 페이지를 계속 읽어 보십시오. 
---
= Cloud Manager의 중요한 변경 사항
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
이 페이지에서는 새로운 개선 사항을 도입하면서 서비스를 사용하는 데 도움이 되는 Cloud Manager의 중요한 변경 사항을 소개합니다. 를 계속 읽어야 합니다 link:reference_new_occm.html["새로운 소식"] 페이지를 클릭하여 모든 새로운 기능 및 향상된 기능에 대해 알아보십시오.



== SaaS 변경

우리는 Cloud Manager를 위한 서비스형 소프트웨어 경험을 도입했습니다. 새로운 경험을 통해 Cloud Manager를 더욱 쉽게 사용하고 NetApp은 하이브리드 클라우드 인프라를 관리하는 추가 기능을 제공할 수 있습니다.

* link:concept_saas.html["Cloud Manager를 SaaS로 전환"]
* link:concept_overview.html["Cloud Manager의 작동 방식에 대해 알아보십시오"]




== 시스템 유형 변경

Cloud Manager의 새로운 기능과 향후 기능에 적절한 리소스를 제공하기 위해 다음과 같이 필요한 최소 인스턴스, VM 및 시스템 유형을 변경했습니다.

* AWS:T3.xLarge
* Azure:DS3 v2
* GCP: n1-standard-4


시스템 유형을 업그레이드하면 새로운 Kubernetes 환경, 글로벌 파일 캐시, 모니터링 등과 같은 기능에 액세스할 수 있습니다.

이러한 기본 크기는 지원되는 최소값입니다 link:reference_cloud_mgr_reqs.html["CPU 및 RAM 요구 사항을 기반으로 합니다"].

Cloud Manager에서 커넥터의 시스템 유형을 변경하는 지침을 표시합니다.



== 계정 설정

Cloud Central 계정은 멀티 테넌시를 제공하고, 격리된 작업 영역에서 사용자와 리소스를 구성하고, 커넥터 및 구독에 대한 액세스를 관리하는 데 도움이 됩니다.

* link:concept_cloud_central_accounts.html["사용자, 작업 영역, 커넥터 및 가입과 같은 Cloud Central 계정에 대해 알아봅니다"]
* link:task_setting_up_cloud_central_accounts.html["계정을 시작하는 방법에 대해 알아보십시오"]
* link:task_managing_cloud_central_accounts.html["계정을 설정한 후 계정을 관리하는 방법에 대해 알아봅니다"]




== 새 권한

새로운 기능과 향상된 기능을 도입함에 따라 Cloud Manager에 추가 클라우드 공급자 권한이 필요한 경우가 있습니다. 이 섹션에서는 현재 필요한 새 사용 권한을 식별합니다.

에서 최신 사용 권한 목록을 찾을 수 있습니다 https://mysupport.netapp.com/site/info/cloud-manager-policies["Cloud Manager 정책 페이지"^].



=== 설치하고

3.8.1 릴리즈부터 Cloud Volumes ONTAP를 사용하여 클라우드로 백업을 사용하려면 다음 권한이 필요합니다. link:task_backup_to_s3.html["자세한 정보"].

[source, json]
----
{
            "Sid": "backupPolicy",
            "Effect": "Allow",
            "Action": [
                "s3:DeleteBucket",
                "s3:GetLifecycleConfiguration",
                "s3:PutLifecycleConfiguration",
                "s3:PutBucketTagging",
                "s3:ListBucketVersions",
                "s3:GetObject",
                "s3:ListBucket",
                "s3:ListAllMyBuckets",
                "s3:GetBucketTagging",
                "s3:GetBucketLocation",
                "s3:GetBucketPolicyStatus",
                "s3:GetBucketPublicAccessBlock",
                "s3:GetBucketAcl",
                "s3:GetBucketPolicy",
                "s3:PutBucketPublicAccessBlock"
            ],
            "Resource": [
                "arn:aws:s3:::netapp-backup-*"
            ]
        },
----


=== Azure를 지원합니다

* Azure 배포 오류를 방지하려면 Azure의 Cloud Manager 정책에 다음 권한이 포함되어 있는지 확인하십시오.
+
[source, json]
----
"Microsoft.Resources/deployments/operationStatuses/read"
----
* 3.8.7 릴리즈부터 다른 계정의 외부 키를 사용하여 단일 노드 Cloud Volumes ONTAP 시스템에서 Azure 관리 디스크를 암호화하려면 다음 권한이 필요합니다. link:reference_new_occm.html#cloud-volumes-ontap-enhancements["자세한 정보"].
+
[source, json]
----
"Microsoft.Compute/diskEncryptionSets/read"
----
* Cloud Volumes ONTAP에서 글로벌 파일 캐시를 설정하려면 다음 권한이 필요합니다. link:concept_gfc.html["자세한 정보"].
+
[source, json]
----
"Microsoft.Resources/deployments/operationStatuses/read",
"Microsoft.Insights/Metrics/Read",
"Microsoft.Compute/virtualMachines/extensions/write",
"Microsoft.Compute/virtualMachines/extensions/read",
"Microsoft.Compute/virtualMachines/extensions/delete",
"Microsoft.Compute/virtualMachines/delete",
"Microsoft.Network/networkInterfaces/delete",
"Microsoft.Network/networkSecurityGroups/delete",
"Microsoft.Resources/deployments/delete",
----




=== GCP



==== Kubernetes 관리에 대한 새로운 권한

3.8.8 릴리즈부터 Connector의 서비스 계정에 대해 GKE(Google Kubernetes Engine)에서 실행되는 Kubernetes 클러스터를 검색하고 관리할 수 있는 다음과 같은 권한이 필요합니다.

[source, yaml]
----
- container.*
----


==== 데이터 계층화를 위한 새로운 권한

3.8 릴리즈부터 데이터 계층화에 서비스 계정을 사용하려면 다음 권한이 필요합니다. link:reference_new_occm.html#data-tiering-enhancements-in-gcp["자세한 정보"].

[source, yaml]
----
- storage.buckets.update
- compute.instances.setServiceAccount
- iam.serviceAccounts.getIamPolicy
- iam.serviceAccounts.list
----


== 새 끝점

Connector를 사용하려면 공용 클라우드 환경 내의 리소스와 프로세스를 관리하기 위한 아웃바운드 인터넷 액세스가 필요합니다. 이 섹션에서는 현재 필요한 새 끝점을 식별합니다.

에서 찾을 수 있습니다 link:reference_networking.html["웹 브라우저에서 액세스할 수 있는 엔드포인트의 전체 목록은 여기 를 참조하십시오"] 및 .

* 사용자는 다음 엔드포인트에 연결하여 웹 브라우저에서 Cloud Manager에 액세스해야 합니다.
+
https://cloudmanager.netapp.com 으로 문의하십시오

* Docker 인프라를 위한 컨테이너 구성 요소의 소프트웨어 이미지를 얻으려면 커넥터는 다음 끝점에 액세스해야 합니다.
+
https://cloudmanagerinfraprod.azurecr.io 으로 문의하십시오

+
방화벽이 Connector에서 이 끝점에 대한 액세스를 활성화하는지 확인합니다.


