---
sidebar: sidebar 
permalink: reference_cloud_mgr_reqs.html 
keywords: configurations, ec2, vm, ports, ram, operating system, os, host, requirement, requirements, hypervisor, disk, space, mysql, centos, rhel, red hat, cpu, disk space, 3306 
summary: Connector 소프트웨어는 특정 운영 체제 요구 사항, RAM 요구 사항, 포트 요구 사항 등을 충족하는 호스트에서 실행되어야 합니다. 
---
= 커넥터 호스트 요구 사항
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Connector 소프트웨어는 특정 운영 체제 요구 사항, RAM 요구 사항, 포트 요구 사항 등을 충족하는 호스트에서 실행되어야 합니다.

전용 호스트가 필요합니다:: 다른 애플리케이션과 공유되는 호스트에서는 Connector가 지원되지 않습니다. 호스트는 전용 호스트여야 합니다.
CPU:: 코어 4개 또는 vCPU 4개
RAM:: 14GB
AWS EC2 인스턴스 유형:: 위의 CPU 및 RAM 요구 사항을 충족하는 인스턴스 유형입니다. T3.xLarge를 사용하고 Cloud Manager에서 직접 Connector를 배포할 때 해당 인스턴스 유형을 사용하는 것이 좋습니다.
Azure VM 크기입니다:: 위의 CPU 및 RAM 요구 사항을 충족하는 인스턴스 유형입니다. Connector를 Cloud Manager에서 직접 배포할 때는 DS3 v2를 사용하고 해당 VM 크기를 사용하는 것이 좋습니다.
GCP 시스템 유형입니다:: 위의 CPU 및 RAM 요구 사항을 충족하는 인스턴스 유형입니다. n1-standard-4를 사용하고 Cloud Manager에서 직접 Connector를 구축할 때는 해당 시스템 유형을 사용하는 것이 좋습니다.
지원되는 운영 체제::
+
--
* CentOS 7.6
* CentOS 7.7
* Red Hat Enterprise Linux 7.6
* Red Hat Enterprise Linux 7.7
+
Red Hat Enterprise Linux 시스템은 Red Hat 서브스크립션 관리 에 등록되어 있어야 합니다. 등록되지 않은 경우 시스템은 Connector 설치 중에 필요한 타사 소프트웨어를 업데이트하기 위해 리포지토리에 액세스할 수 없습니다.

+
Connector는 이러한 운영 체제의 영어 버전에서 지원됩니다.



--
하이퍼바이저:: CentOS 또는 Red Hat Enterprise Linux 실행 인증을 받은 베어 메탈 또는 호스팅된 하이퍼바이저https://access.redhat.com/certified-hypervisors["Red Hat 솔루션: Red Hat Enterprise Linux 실행 인증을 받은 하이퍼바이저는 무엇입니까?"^]
/opt의 디스크 공간입니다:: 100GB의 공간을 사용할 수 있어야 합니다
아웃바운드 인터넷 액세스:: Connector를 설치하고 Connector가 퍼블릭 클라우드 환경 내의 리소스 및 프로세스를 관리하려면 아웃바운드 인터넷 액세스가 필요합니다. 끝점 목록은 을 참조하십시오 link:reference_networking_cloud_manager.html["커넥터에 대한 네트워킹 요구 사항"].

