---
sidebar: sidebar 
permalink: task_scanning_onprem.html 
keywords: cloud compliance, on-prem, scan on prem data, scan on-prem data 
summary: 온프레미스 데이터를 Cloud Volumes ONTAP 작업 환경으로 복제하고 규정 준수를 활성화하여 클라우드 규정 준수를 통해 사내 ONTAP 데이터를 스캔할 수 있습니다. 온-프레미스 ONTAP 작업 환경에서 직접 데이터를 스캔하는 것은 지원되지 않습니다. 
---
= SnapMirror를 사용하여 클라우드 규정 준수 기능을 통해 사내 ONTAP 데이터를 스캔합니다
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
온프레미스 NFS 또는 CIFS 데이터를 Cloud Volumes ONTAP 작업 환경에 복제하고 규정 준수를 설정하여 온프레미스 ONTAP 데이터를 클라우드 규정 준수 로 스캔할 수 있습니다. 온-프레미스 ONTAP 작업 환경에서 직접 데이터를 스캔하는 것은 지원되지 않습니다.

이(가) 있어야 합니다 link:task_deploy_cloud_compliance.html["Cloud Manager에 이미 클라우드 규정 준수 인스턴스를 배포했습니다"^].

.단계
. Cloud Manager에서 사내 ONTAP 클러스터와 Cloud Volumes ONTAP 간에 SnapMirror 관계를 생성합니다.
+
.. https://docs.netapp.com/us-en/occm/task_discovering_ontap.html["Cloud Manager에서 사내 클러스터를 검색합니다"^].
.. https://docs.netapp.com/us-en/occm/task_replicating_data.html["Cloud Manager에서 사내 ONTAP 클러스터와 Cloud Volumes ONTAP 간에 SnapMirror 복제를 생성합니다"^].


. SMB 소스 볼륨에서 생성된 DP 볼륨의 경우, ONTAP CLI에서 데이터 액세스를 위한 SMB 대상 볼륨을 구성합니다. (Cloud Compliance를 통해 데이터 액세스가 자동으로 설정되므로 NFS 볼륨에는 이 작업이 필요하지 않습니다.)
+
.. http://docs.netapp.com/ontap-9/topic/com.netapp.doc.pow-cifs-cg/GUID-371B7797-B5BE-4B19-BDE4-BBC938F109BF.html["타겟 볼륨에 SMB 공유를 생성합니다"^].
.. http://docs.netapp.com/ontap-9/topic/com.netapp.doc.pow-cifs-cg/GUID-90FCFDB3-F60C-4685-9BBD-6D648F75701C.html["대상 볼륨의 SMB 공유에 적절한 ACL을 적용합니다"^].


. Cloud Manager에서 SnapMirror 데이터가 포함된 Cloud Volumes ONTAP 작업 환경에서 클라우드 규정 준수를 활성화합니다.
+
.. 작업 환경 * 을 클릭합니다.
.. SnapMirror 데이터가 포함된 작업 환경을 선택하고 * 규정 준수 활성화 * 를 클릭합니다.
+
link:task_getting_started_compliance.html["Cloud Volumes ONTAP 시스템에서 클라우드 규정 준수를 지원하는 데 도움이 필요한 경우 여기를 클릭하십시오"^].

.. Scan Configuration_page 상단의 * Enable Access to DP volumes * 버튼을 클릭합니다.
.. 스캔할 각 DP 볼륨을 활성화하거나 모든 볼륨 * 컨트롤에 대해 * 규정 준수 활성화 를 사용하여 모든 DP 볼륨을 포함한 모든 볼륨을 활성화합니다.




을 참조하십시오 link:task_getting_started_compliance.html#scanning-data-protection-volumes["데이터 보호 볼륨을 검색하는 중입니다"^] DP 볼륨 스캔에 대한 자세한 내용은 를 참조하십시오.
