---
sidebar: sidebar 
permalink: task_provisioning_storage.html 
keywords: storage, provisioning, iscsi, nfs, cifs, volumes, aggregates, provision, create, quotas, nas, san, LUNs, quotas, qtree, add, advanced allocation, create a volume, add a volume, create volumes, add volumes, creating a volume, adding a volume, creating aggregates, adding an aggregate, add an aggregate, create an aggregate, provision volume, provision a volume, provisioning volumes, create a LUN, create LUNs, create LUN, provision LUNs, add volume to second node, add volume to node 2, flexcache, flexcache volumes, create a flexcache volume, provision flexcache, create flexcache volume 
summary: 볼륨 및 애그리게이트를 관리하여 Cloud Manager에서 Cloud Volumes ONTAP 시스템에 대한 추가 NFS, CIFS 및 iSCSI 스토리지를 프로비저닝할 수 있습니다. 
---
= 스토리지 프로비저닝
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
볼륨 및 애그리게이트를 관리하여 Cloud Manager에서 Cloud Volumes ONTAP 시스템에 대한 추가 스토리지를 프로비저닝할 수 있습니다.


IMPORTANT: 모든 디스크와 애그리게이트는 Cloud Manager에서 직접 생성 및 삭제해야 합니다. 다른 관리 도구에서 이러한 작업을 수행해서는 안 됩니다. 이렇게 하면 시스템 안정성에 영향을 주고 향후 디스크를 추가할 수 없도록 하며 중복 클라우드 공급자 비용을 생성할 수 있습니다.



== FlexVol 볼륨을 생성하는 중입니다

Cloud Volumes ONTAP 시스템을 시작한 후 더 많은 스토리지가 필요한 경우 Cloud Manager에서 NFS, CIFS 또는 iSCSI에 대한 새 FlexVol 볼륨을 생성할 수 있습니다.

iSCSI 볼륨을 생성할 때 Cloud Manager에서 자동으로 LUN을 생성합니다. 볼륨 당 하나의 LUN만 생성하므로 관리가 필요 없습니다. 볼륨을 생성한 후 <<Connecting a LUN to a host,IQN을 사용하여 호스트에서 LUN에 연결합니다>>.


NOTE: System Manager 또는 CLI에서 추가 LUN을 생성할 수 있습니다.

AWS에서 CIFS를 사용하려면 DNS와 Active Directory를 설정해야 합니다. 자세한 내용은 을 참조하십시오 link:reference_networking_aws.html["Cloud Volumes ONTAP for AWS의 네트워킹 요구사항"].

.단계
. 작업 환경 페이지에서 FlexVol 볼륨을 프로비저닝할 Cloud Volumes ONTAP 시스템의 이름을 두 번 클릭합니다.
. Aggregate 또는 특정 Aggregate에 새 볼륨을 생성합니다.
+
[cols="30,70"]
|===
| 조치 | 단계 


| 새 볼륨을 생성하고 Cloud Manager가 포함된 애그리게이트를 선택하도록 합니다 | 새 볼륨 추가 * 를 클릭합니다. 


| 특정 애그리게이트에 새 볼륨을 생성합니다  a| 
.. 메뉴 아이콘을 클릭한 다음 * 고급 > 고급 할당 * 을 클릭합니다.
.. 집계 메뉴를 클릭합니다.
.. 볼륨 생성 * 을 클릭합니다.


|===
. 새 볼륨에 대한 세부 정보를 입력한 다음 * 계속 * 을 클릭합니다.
+
이 페이지의 일부 필드는 설명이 필요 없습니다. 다음 표에서는 지침이 필요한 필드를 설명합니다.

+
[cols="25,75"]
|===
| 필드에 입력합니다 | 설명 


| 크기 | 입력할 수 있는 최대 크기는 씬 프로비저닝의 사용 여부에 따라 크게 달라집니다. 이를 통해 현재 사용 가능한 물리적 스토리지보다 더 큰 볼륨을 생성할 수 있습니다. 


| 액세스 제어(NFS에만 해당) | 엑스포트 정책은 볼륨에 액세스할 수 있는 서브넷의 클라이언트를 정의합니다. 기본적으로 Cloud Manager는 서브넷의 모든 인스턴스에 대한 액세스를 제공하는 값을 입력합니다. 


| 권한 및 사용자/그룹(CIFS 전용) | 이러한 필드를 사용하면 사용자 및 그룹의 공유에 대한 액세스 수준(액세스 제어 목록 또는 ACL라고도 함)을 제어할 수 있습니다. 로컬 또는 도메인 Windows 사용자 또는 그룹, UNIX 사용자 또는 그룹을 지정할 수 있습니다. 도메인 Windows 사용자 이름을 지정하는 경우 domain\username 형식을 사용하여 사용자의 도메인을 포함해야 합니다. 


| 스냅샷 정책 | 스냅샷 복사본 정책은 자동으로 생성되는 NetApp 스냅샷 복사본의 수와 빈도를 지정합니다. NetApp 스냅샷 복사본은 성능 영향이 없고 최소한의 스토리지가 필요한 시점 파일 시스템 이미지입니다. 기본 정책을 선택하거나 선택하지 않을 수 있습니다. Microsoft SQL Server의 tempdb와 같이 임시 데이터에 대해 없음을 선택할 수 있습니다. 


| 고급 옵션(NFS에만 해당) | 볼륨의 NFS 버전 선택: NFSv3 또는 NFSv4 


| 이니시에이터 그룹 및 IQN(iSCSI 전용) | iSCSI 스토리지 타겟을 LUN(논리 유닛)이라고 하며 호스트에 표준 블록 디바이스로 표시됩니다. 이니시에이터 그룹은 iSCSI 호스트 노드 이름의 테이블이며 어떤 이니시에이터가 어떤 LUN을 액세스할 수 있는지 제어합니다. iSCSI 대상은 표준 이더넷 네트워크 어댑터(NIC), 소프트웨어 이니시에이터가 있는 TCP 오프로드 엔진(TOE) 카드, 통합 네트워크 어댑터(CNA) 또는 전용 호스트 파스트 어댑터(HBA)를 통해 네트워크에 연결되며 iSCSI 공인 이름(IQN)으로 식별됩니다. iSCSI 볼륨을 생성할 때 Cloud Manager에서 자동으로 LUN을 생성합니다. 볼륨 당 하나의 LUN만 생성하므로 관리가 필요 없습니다. 볼륨을 생성한 후 link:task_provisioning_storage.html#connecting-a-lun-to-a-host["IQN을 사용하여 호스트에서 LUN에 연결합니다"]. 
|===
. CIFS 프로토콜을 선택하고 CIFS 서버가 설정되지 않은 경우 CIFS 서버 생성 대화 상자에서 서버에 대한 세부 정보를 지정한 다음 * 저장 후 계속 * 을 클릭합니다.
+
[cols="30,70"]
|===
| 필드에 입력합니다 | 설명 


| DNS 기본 및 보조 IP 주소 | CIFS 서버에 대한 이름 확인을 제공하는 DNS 서버의 IP 주소입니다. 나열된 DNS 서버에는 CIFS 서버가 연결할 도메인의 Active Directory LDAP 서버 및 도메인 컨트롤러를 찾는 데 필요한 서비스 위치 레코드(SRV)가 포함되어 있어야 합니다. 


| 연결할 Active Directory 도메인입니다 | CIFS 서버를 연결할 AD(Active Directory) 도메인의 FQDN입니다. 


| 도메인에 가입하도록 승인된 자격 증명입니다 | AD 도메인 내의 지정된 OU(조직 구성 단위)에 컴퓨터를 추가할 수 있는 충분한 권한이 있는 Windows 계정의 이름 및 암호입니다. 


| CIFS 서버 NetBIOS 이름입니다 | AD 도메인에서 고유한 CIFS 서버 이름입니다. 


| 조직 구성 단위  a| 
CIFS 서버와 연결할 AD 도메인 내의 조직 단위입니다. 기본값은 CN=Computers입니다.

** AWS 관리 Microsoft AD를 Cloud Volumes ONTAP용 AD 서버로 구성하려면 이 필드에 * OU=Computers, OU=Corp * 를 입력해야 합니다.
** Azure AD 도메인 서비스를 Cloud Volumes ONTAP용 AD 서버로 구성하려면 이 필드에 * OU=ADDC 컴퓨터 * 또는 * OU=ADDC 사용자 * 를 입력해야 합니다.https://docs.microsoft.com/en-us/azure/active-directory-domain-services/create-ou["Azure 설명서: Azure AD 도메인 서비스 관리 도메인에 OU(조직 구성 단위)를 만듭니다"^]




| DNS 도메인 | SVM(Cloud Volumes ONTAP 스토리지 가상 머신)용 DNS 도메인 대부분의 경우 도메인은 AD 도메인과 동일합니다. 


| NTP 서버 | Active Directory DNS를 사용하여 NTP 서버를 구성하려면 * Active Directory 도메인 사용 * 을 선택합니다. 다른 주소를 사용하여 NTP 서버를 구성해야 하는 경우 API를 사용해야 합니다. 를 참조하십시오 link:api.html["Cloud Manager API 개발자 가이드 를 참조하십시오"^] 를 참조하십시오. 
|===
. Usage Profile, Disk Type 및 Tiering Policy 페이지에서 스토리지 효율성 기능을 사용할지, 디스크 유형을 선택하고 필요한 경우 계층화 정책을 편집할지 여부를 선택합니다.
+
자세한 내용은 다음을 참조하십시오.

+
** link:task_planning_your_config.html#choosing-a-volume-usage-profile["볼륨 사용 프로필 이해"]
** link:task_planning_your_config.html#sizing-your-system-in-aws["AWS에서 시스템 사이징"]
** link:task_planning_your_config.html#sizing-your-system-in-azure["Azure에서 시스템 사이징"]
** link:concept_data_tiering.html["데이터 계층화 개요"]


. Go * 를 클릭합니다.


Cloud Volumes ONTAP가 볼륨을 프로비저닝합니다.

CIFS 공유를 프로비저닝한 경우 파일 및 폴더에 대한 사용자 또는 그룹 권한을 제공하고 해당 사용자가 공유를 액세스하고 파일을 생성할 수 있는지 확인합니다.

볼륨에 할당량을 적용하려면 System Manager 또는 CLI를 사용해야 합니다. 할당량을 사용하면 사용자, 그룹 또는 qtree가 사용하는 파일 수와 디스크 공간을 제한하거나 추적할 수 있습니다.



== HA 구성의 두 번째 노드에서 FlexVol 볼륨 생성

기본적으로 Cloud Manager는 HA 구성의 첫 번째 노드에 볼륨을 생성합니다. 두 노드에서 모두 클라이언트에 데이터를 제공하는 액티브-액티브 구성이 필요한 경우 두 번째 노드에서 애그리게이트와 볼륨을 생성해야 합니다.

.단계
. 작업 환경 페이지에서 애그리게이트를 관리할 Cloud Volumes ONTAP 작업 환경의 이름을 두 번 클릭합니다.
. 메뉴 아이콘을 클릭한 다음 * 고급 > 고급 할당 * 을 클릭합니다.
. Add Aggregate * 를 클릭한 다음 Aggregate를 생성합니다.
. 홈 노드의 경우 HA 쌍의 두 번째 노드를 선택합니다.
. Cloud Manager에서 애그리게이트를 생성한 후, 애그리게이트를 선택하고 * 볼륨 생성 * 을 클릭합니다.
. 새 볼륨에 대한 세부 정보를 입력한 다음 * Create * 를 클릭합니다.


필요한 경우 이 애그리게이트에 볼륨을 추가로 생성할 수 있습니다.


IMPORTANT: 여러 AWS Availability Zone에 구축된 HA 쌍의 경우 볼륨이 상주하는 노드의 부동 IP 주소를 사용하여 볼륨을 클라이언트에 마운트해야 합니다.



== 애그리게이트 생성

볼륨을 직접 생성하거나 Cloud Manager에서 볼륨을 생성할 때 자동으로 애그리게이트를 생성할 수 있습니다. 애그리게이트를 직접 생성할 때의 이점은 기본 디스크 크기를 선택할 수 있다는 것입니다. 이를 통해 필요한 용량 또는 성능에 맞게 애그리게이트를 크기를 조정할 수 있습니다.

.단계
. 작업 환경 페이지에서 애그리게이트를 관리할 Cloud Volumes ONTAP 인스턴스의 이름을 두 번 클릭합니다.
. 메뉴 아이콘을 클릭한 다음 * 고급 > 고급 할당 * 을 클릭합니다.
. Add Aggregate * 를 클릭한 다음 Aggregate에 대한 세부 정보를 지정합니다.
+
디스크 유형 및 디스크 크기에 대한 도움말은 를 참조하십시오 link:task_planning_your_config.html["구성 계획"].

. Go * 를 클릭한 다음 * Approve and Purchase * 를 클릭합니다.




== 호스트에 LUN 연결

iSCSI 볼륨을 생성할 때 Cloud Manager에서 자동으로 LUN을 생성합니다. 볼륨 당 하나의 LUN만 생성하므로 관리가 필요 없습니다. 볼륨을 생성한 후 IQN을 사용하여 호스트에서 LUN에 연결합니다.

다음 사항에 유의하십시오.

. Cloud Manager의 자동 용량 관리는 LUN에 적용되지 않습니다. Cloud Manager에서 LUN을 생성하면 자동 확장 기능이 해제됩니다.
. System Manager 또는 CLI에서 추가 LUN을 생성할 수 있습니다.


.단계
. 작업 환경 페이지에서 볼륨을 관리할 Cloud Volumes ONTAP 작업 환경을 두 번 클릭합니다.
. 볼륨을 선택한 다음 * 대상 IQN * 을 클릭합니다.
. IQN 이름을 복사하려면 * Copy * 를 클릭합니다.
. 호스트에서 LUN으로의 iSCSI 접속을 설정합니다.
+
** http://docs.netapp.com/ontap-9/topic/com.netapp.doc.exp-iscsi-rhel-cg/GUID-15E8C226-BED5-46D0-BAED-379EA4311340.html["Red Hat Enterprise Linux용 ONTAP 9 iSCSI Express 구성: 대상으로 iSCSI 세션 시작"^]
** http://docs.netapp.com/ontap-9/topic/com.netapp.doc.exp-iscsi-cpg/GUID-857453EC-90E9-4AB6-B543-83827CF374BF.html["Windows용 ONTAP 9 iSCSI Express 구성: 타겟으로 iSCSI 세션 시작"^]






== FlexCache 볼륨을 사용하여 데이터 액세스 가속화

FlexCache 볼륨은 원본(또는 소스) 볼륨의 NFS 읽기 데이터를 캐싱하는 스토리지 볼륨입니다. 이후에 캐싱된 데이터를 읽으면 해당 데이터에 더 빠르게 액세스할 수 있습니다.

FlexCache 볼륨을 사용하면 데이터 액세스 속도를 높이거나 자주 액세스하는 볼륨에서 트래픽을 오프로드할 수 있습니다. FlexCache 볼륨은 원본 볼륨에 액세스하지 않고도 직접 데이터를 제공할 수 있으므로 클라이언트가 동일한 데이터에 반복적으로 액세스해야 할 때 성능을 개선할 수 있습니다. FlexCache 볼륨은 읽기 집약적인 시스템 워크로드에 적합합니다.

Cloud Manager에서는 현재 FlexCache 볼륨을 관리할 수 없지만 ONTAP CLI 또는 ONTAP System Manager를 사용하여 FlexCache 볼륨을 생성하고 관리할 수 있습니다.

* http://docs.netapp.com/ontap-9/topic/com.netapp.doc.pow-fc-mgmt/home.html["빠른 데이터 액세스를 위한 FlexCache 볼륨 전원 가이드"^]
* http://docs.netapp.com/ontap-9/topic/com.netapp.doc.onc-sm-help-960/GUID-07F4C213-076D-4FE8-A8E3-410F49498D49.html["System Manager에서 FlexCache 볼륨 생성"^]


3.7.2 릴리스부터는 Cloud Manager에서 모든 새 Cloud Volumes ONTAP 시스템에 대한 FlexCache 라이센스를 생성합니다. 이 라이센스에는 500GB의 사용 제한이 포함되어 있습니다.


NOTE: 라이센스를 생성하려면 Cloud Manager에서 \https://ipa-signer.cloudmanager.netapp.com 에 액세스해야 합니다. 방화벽에서 이 URL에 액세스할 수 있는지 확인합니다.

video::PBNPVRUeT1o[youtube,width=848,height=480]