---
sidebar: sidebar 
permalink: task_getting_started_gcp.html 
keywords: google cloud platform, gcp, deploy cloud manager, launch cloud manager, create cloud manager, getting started, networking, gcp networking, service account, tiering, data tiering, bucket, fabricpool, storage access key, gcp role, role, iam role, permissions, gcp permissions 
summary: 몇 가지 단계를 통해 Cloud Volumes ONTAP for GCP를 시작해 보십시오. 
---
= Google Cloud용 Cloud Volumes ONTAP 시작하기
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
몇 가지 단계를 통해 Cloud Volumes ONTAP for GCP를 시작해 보십시오.



==== 커넥터를 작성합니다

[role="quick-margin-para"]
가 없는 경우 link:concept_connectors.html["커넥터"] 그러나 계정 관리자는 계정을 만들어야 합니다. link:task_creating_connectors_gcp.html["GCP에서 커넥터를 생성하는 방법을 알아보십시오"].

[role="quick-margin-para"]
첫 번째 Cloud Volumes ONTAP 작업 환경을 생성할 때 아직 커넥터가 없는 경우 Cloud Manager에서 커넥터를 배포할지 묻는 메시지를 표시합니다.



==== 구성을 계획합니다

[role="quick-margin-para"]
Cloud Manager는 워크로드 요구사항에 맞게 사전 구성된 패키지를 제공하거나 자체 구성을 생성할 수 있습니다. 자신의 구성을 선택하는 경우 사용 가능한 옵션을 이해해야 합니다. link:task_planning_your_config_gcp.html["자세한 정보"].



==== 네트워크 설정

. VPC와 서브넷이 커넥터와 Cloud Volumes ONTAP 간의 연결을 지원하는지 확인합니다.
. 커넥터 및 Cloud Volumes ONTAP가 여러 엔드포인트에 연결할 수 있도록 타겟 VPC에서 아웃바운드 인터넷 액세스를 활성화합니다.
+
이 단계는 커넥터가 아웃바운드 인터넷 액세스 없이 Cloud Volumes ONTAP를 관리할 수 없기 때문에 중요합니다. 아웃바운드 연결을 제한해야 하는 경우 의 끝점 목록을 참조하십시오 link:reference_networking_gcp.html["커넥터 및 Cloud Volumes ONTAP"].



[role="quick-margin-para"]
link:reference_networking_gcp.html["네트워킹 요구 사항에 대해 자세히 알아보십시오"].



==== 데이터 계층화에 GCP를 설정합니다

[role="quick-margin-para"]
Cloud Volumes ONTAP에서 저렴한 오브젝트 스토리지(Google 클라우드 스토리지 버킷)로 콜드 데이터를 계층화하려면 다음 두 가지 요구사항이 충족되어야 합니다.

. https://cloud.google.com/vpc/docs/configure-private-google-access["개인 Google 액세스를 위한 Cloud Volumes ONTAP 서브넷을 구성합니다"^].
. https://cloud.google.com/iam/docs/creating-managing-service-accounts#creating_a_service_account["데이터 계층화를 위한 서비스 계정 설정"^]:
+
** Predefined_Storage Admin_role을 계층화 서비스 계정에 할당합니다.
** Connector 서비스 계정을 계층화 서비스 계정에 _ 서비스 계정 사용자 _ 로 추가합니다.
+
사용자 역할을 제공할 수 있습니다 https://cloud.google.com/iam/docs/creating-managing-service-accounts#creating_a_service_account["계층화 서비스 계정을 생성할 때 마법사의 3단계에서"], 또는 https://cloud.google.com/iam/docs/granting-roles-to-service-accounts#granting_access_to_a_user_for_a_service_account["서비스 계정이 생성된 후 역할을 부여합니다"^].

+
Cloud Volumes ONTAP 작업 환경을 생성할 때 나중에 계층화 서비스 계정을 선택해야 합니다.

+
Cloud Volumes ONTAP 시스템을 생성할 때 데이터 계층화를 사용하지 않고 서비스 계정을 선택하지 않은 경우, 시스템을 끄고 GCP 콘솔에서 Cloud Volumes ONTAP에 서비스 계정을 추가해야 합니다.







==== Google Cloud API를 활성화합니다

[role="quick-margin-para"]
https://cloud.google.com/apis/docs/getting-started#enabling_apis["프로젝트에서 다음 Google Cloud API를 활성화합니다"^]. 이러한 API는 Connector 및 Cloud Volumes ONTAP를 구축하는 데 필요합니다.

* Cloud Deployment Manager V2 API
* 클라우드 로깅 API
* Cloud Resource Manager API를 참조하십시오
* 컴퓨팅 엔진 API
* IAM(Identity and Access Management) API




==== Cloud Manager를 사용하여 Cloud Volumes ONTAP를 실행합니다

[role="quick-margin-para"]
작업 환경 추가 * 를 클릭하고 배포할 시스템 유형을 선택한 다음 마법사의 단계를 완료합니다. link:task_deploying_gcp.html["단계별 지침을 읽습니다"].

.관련 링크
* link:concept_evaluating.html["평가 중"]
* link:task_creating_connectors_gcp.html["Cloud Manager에서 커넥터 생성"]
* link:task_installing_linux.html["Linux 호스트에 Connector 소프트웨어 설치"]
* link:reference_permissions.html#what-cloud-manager-does-with-gcp-permissions["Cloud Manager에서 GCP 권한으로 수행하는 권한입니다"]

