---
sidebar: sidebar 
permalink: task_getting_started_aws.html 
keywords: amazon web services, aws, netapp, data fabric, hybrid cloud, cloud, public cloud, networking, vpc, quick, getting started, install, installing, deploy, deploying, setup, setting up, launching, requirements, prerequisites, cloud central, get started, network, vpn, multi-cloud, tier, tiering, storage tier, data tier, vpc endpoint, endpoint, S3, subscribe, subscribing, marketplace, granting, permissions, policy, iam policy, ec2 console, ami, mediator, connectivity, internet, outbound, endpoint, connection, networks, replicating, ec2 service, policies, attach, iam user, access key, secret key, keys, sign up, cloud manager, cloud volumes ontap, cloud ontap, create 
summary: 몇 가지 단계로 Cloud Volumes ONTAP for AWS를 시작하십시오. 
---
= Cloud Volumes ONTAP for AWS 시작하기
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
몇 가지 단계로 Cloud Volumes ONTAP for AWS를 시작하십시오.



==== 커넥터를 작성합니다

[role="quick-margin-para"]
가 없는 경우 link:concept_connectors.html["커넥터"] 그러나 계정 관리자는 계정을 만들어야 합니다. .

[role="quick-margin-para"]
첫 번째 Cloud Volumes ONTAP 작업 환경을 생성할 때 아직 커넥터가 없는 경우 Cloud Manager에서 커넥터를 배포할지 묻는 메시지를 표시합니다.



==== 구성을 계획합니다

[role="quick-margin-para"]
Cloud Manager는 워크로드 요구사항에 맞게 사전 구성된 패키지를 제공하거나 자체 구성을 생성할 수 있습니다. 자신의 구성을 선택하는 경우 사용 가능한 옵션을 이해해야 합니다. link:task_planning_your_config.html["자세한 정보"].



==== 네트워크 설정

. VPC와 서브넷이 커넥터와 Cloud Volumes ONTAP 간의 연결을 지원하는지 확인합니다.
. 커넥터 및 Cloud Volumes ONTAP가 여러 엔드포인트에 연결할 수 있도록 타겟 VPC에서 아웃바운드 인터넷 액세스를 활성화합니다.
+
이 단계는 커넥터가 아웃바운드 인터넷 액세스 없이 Cloud Volumes ONTAP를 관리할 수 없기 때문에 중요합니다. 아웃바운드 연결을 제한해야 하는 경우 의 끝점 목록을 참조하십시오 link:reference_networking_aws.html["커넥터 및 Cloud Volumes ONTAP"].

. VPC 엔드포인트를 S3 서비스로 설정합니다.
+
Cloud Volumes ONTAP의 콜드 데이터를 저비용 오브젝트 스토리지로 계층화하려는 경우 VPC 엔드포인트가 필요합니다.



[role="quick-margin-para"]
link:reference_networking_aws.html["네트워킹 요구 사항에 대해 자세히 알아보십시오"].



==== AWS KMS를 설정합니다

[role="quick-margin-para"]
Cloud Volumes ONTAP에서 아마존 암호화를 사용하려면 활성 CMK(고객 마스터 키)가 있는지 확인해야 합니다. 또한 Connector에 대한 권한을 제공하는 IAM 역할을 _KEY USER_로 추가하여 각 CMK에 대한 키 정책을 수정해야 합니다. link:task_setting_up_kms.html["자세한 정보"].



==== Cloud Manager를 사용하여 Cloud Volumes ONTAP를 실행합니다

[role="quick-margin-para"]
작업 환경 추가 * 를 클릭하고 배포할 시스템 유형을 선택한 다음 마법사의 단계를 완료합니다. link:task_deploying_otc_aws.html["단계별 지침을 읽습니다"].

.관련 링크
* link:concept_evaluating.html["평가 중"]
* link:task_creating_connectors_aws.html["Cloud Manager에서 커넥터 생성"]
* link:task_launching_aws_mktp.html["AWS Marketplace에서 커넥터 실행"]
* link:task_installing_linux.html["Linux 호스트에 Connector 소프트웨어 설치"]
* link:reference_permissions.html#what-cloud-manager-does-with-aws-permissions["Cloud Manager에서 AWS 권한을 통해 수행하는 것"]

